"""PDF export for a LegalOpinion. Enforces the same review gate at export
time: an unreviewed opinion can still be exported (so a practitioner has
something to review), but it is always stamped as a draft, never as a
final opinion."""
from __future__ import annotations

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from landtitle.schemas import LegalOpinion

DISCLAIMER = (
    "This document is a research/first-draft accelerator generated by an automated pipeline. "
    "It is NOT a final legal opinion and must not be relied upon until reviewed and signed off "
    "by a licensed legal practitioner."
)

# fpdf2's core "Helvetica" font only supports latin-1. Confirmed live: the
# LLM's own generated prose routinely uses smart/curly punctuation (e.g. a
# right single quote in "GPA's") which crashes multi_cell with
# FPDFUnicodeEncodingException. Map the common cases to ASCII rather than
# switching to a bundled Unicode TTF font, since this is prose text where an
# ASCII fallback reads identically to a human reviewer.
_UNICODE_TO_ASCII = {
    "‘": "'", "’": "'",  # single quotes
    "“": '"', "”": '"',  # double quotes
    "–": "-", "—": "-",  # en/em dash
    "…": "...",  # ellipsis
}


def _sanitize_for_pdf(text: str) -> str:
    for unicode_char, ascii_char in _UNICODE_TO_ASCII.items():
        text = text.replace(unicode_char, ascii_char)
    # Any character still outside latin-1 (e.g. stray OCR artifacts) is
    # dropped rather than left to crash the whole export.
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def _line(pdf: FPDF, h: float, text: str) -> None:
    # fpdf2's multi_cell defaults to new_x=XPos.RIGHT, which leaves the
    # cursor at the right margin (almost no width left) instead of resetting
    # to the left margin — the next multi_cell call then has nowhere to
    # render and raises FPDFException. Every call here must reset explicitly.
    pdf.multi_cell(0, h, _sanitize_for_pdf(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def export_opinion_pdf(opinion: LegalOpinion, output_path: str) -> None:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    if opinion.is_draft:
        pdf.set_text_color(180, 0, 0)
        pdf.set_font("Helvetica", "B", 14)
        _line(pdf, 8, "DRAFT -- NOT REVIEWED -- NOT FOR RELIANCE")
        pdf.ln(2)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)
    _line(pdf, 5, DISCLAIMER)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 16)
    _line(pdf, 10, "Land Title Due Diligence Opinion")
    pdf.ln(2)

    sections = [
        ("Property Summary", opinion.property_summary),
        ("Chain of Ownership", opinion.chain_of_ownership),
        ("Encumbrance Status", opinion.encumbrance_status),
        ("Legal Compliance Check", opinion.legal_compliance_check),
        ("Risk Flags", opinion.risk_flags_narrative),
        ("Overall Recommendation", opinion.overall_recommendation),
    ]
    for title, body in sections:
        pdf.set_font("Helvetica", "B", 12)
        _line(pdf, 8, title)
        pdf.set_font("Helvetica", "", 10)
        _line(pdf, 6, body or "(not available)")
        pdf.ln(3)

    pdf.set_font("Helvetica", "I", 9)
    if opinion.is_draft:
        _line(pdf, 6, "Reviewed by: ___________________________ (pending human review)")
    else:
        _line(pdf, 6, f"Reviewed by: {opinion.reviewed_by}")

    pdf.output(output_path)
